# Generated by Django 4.2.30 on 2026-05-23 01:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('repositorio', '0002_perfil_solicitudcambiorol_remove_usuario_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='categoria',
            field=models.CharField(choices=[('Aprendizaje, conocimiento, tecnologías, comunicación y digitalización', 'Aprendizaje, conocimiento, tecnologías, comunicación y digitalización'), ('Gestión, emprendimiento, organizaciones sociales del conocimiento y aprendizaje', 'Gestión, emprendimiento, organizaciones sociales del conocimiento y aprendizaje'), ('Transmodernidad, naturaleza, ambiente, biodiversidad, ancestralidad y familia', 'Transmodernidad, naturaleza, ambiente, biodiversidad, ancestralidad y familia')], default='Aprendizaje, conocimiento, tecnologías, comunicación y digitalización', max_length=200),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='tipo',
            field=models.CharField(choices=[('Aprendizaje, conocimiento, tecnologías, comunicación y digitalización', 'Aprendizaje, conocimiento, tecnologías, comunicación y digitalización'), ('Gestión, emprendimiento, organizaciones sociales del conocimiento y aprendizaje', 'Gestión, emprendimiento, organizaciones sociales del conocimiento y aprendizaje'), ('Transmodernidad, naturaleza, ambiente, biodiversidad, ancestralidad y familia', 'Transmodernidad, naturaleza, ambiente, biodiversidad, ancestralidad y familia')], default='Aprendizaje, conocimiento, tecnologías, comunicación y digitalización', max_length=200),
        ),
        migrations.CreateModel(
            name='HistorialProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(max_length=20)),
                ('estado_nuevo', models.CharField(max_length=20)),
                ('calificacion', models.FloatField(blank=True, null=True)),
                ('comentario', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('semestre', models.CharField(max_length=20)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_proyectos', to='repositorio.proyecto')),
                ('realizado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
